#!/bin/sh
pkill '^trayer'

monitor="${1:-1}"
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x000000 --height 25 --monitor $monitor &
